version: '3'
networks:
  dev:
services:

  db:
    image: postgres:12
    container_name: dev13_pg12
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - odoodev


  odoo13:
    image: odoo:13
    container_name: dev13_odoo13
    depends_on:
      - db
    ports:
      - 8069:8069
      - 8072:8072
    tty: true
    stdin_open: true
    command: -- --dev=reload
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ../addons:/mnt/extra-addons
      - ./var-lib-odoo:/var/lib/odoo
    restart: unless-stopped
    networks:
      - odoodev


  reverse-proxy:
    container_name: dev13_traefik
    networks:
      - odoodev

    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --providers.file
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    expose: ["80"]
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # config file used for traefik
      - ./traefik.yml:/etc/traefik/traefik.yml:ro