api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: "/etc/traefik/"
    watch: true

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

http:
  routers:
    odoo:
      rule: "Host(`odoo.localhost`)"
      service: "odoo"
    odoochat:
      rule: "Host(`odoo.localhost`) && PathPrefix(`/longpolling`)"
      service: odoochat
    quasar:
      rule: "Host(`odoo.localhost`) && PathPrefix(`/vue`)"
      service: quasar

  services:
    odoo:
      loadBalancer:
        servers:
          - url: "http://odoo13:8069"
    odoochat:
      loadBalancer:
        servers:
          - url: "http://odoo13:8072"
    quasar:
      loadBalancer:
        servers:
          - url: "http://quasar:8081"