api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: "/etc/traefik/"
    watch: true

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

http:
  routers:
    odoo:
      rule: "Host(`localhost`)"
      service: "odoo"
    odoochat:
      rule: "Host(`localhost`) && PathPrefix(`/longpolling`)"
      service: odoochat
    vue:
      rule: "Host(`localhost`) && PathPrefix(`/vue/`, `/sockjs-node`)"
      service: vue

  services:
    odoo:
      loadBalancer:
        servers:
          - url: "http://odoo:8069"
    odoochat:
      loadBalancer:
        servers:
          - url: "http://odoo:8072"
    vue:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:9000"