baseURL = "https://www.odooinvue.org/"
title = "Odoo In Vue"
theme = "ace-documentation"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Docs"
url = "/doc/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3
